services:
  app:
    container_name: app_container
    build: .
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./:/app/:delegated
    env_file:
      - .env
    depends_on:
      - db
      - db-agent 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    dns:
      - 127.0.0.11
      - 8.8.8.8
      - 1.1.1.1

  db:
    image: docker.io/mysql:8
    container_name: mysql_container
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
  db-agent:
    image: docker.io/postgres:16
    container_name: postgres_container
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  mysql_data:
    driver: local
  postgres_data:
    driver: local

